<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    ' Дополнительно визуализировать значение изменения курса.' => 'currency change visualized in graphs',
    ' Тестовое задание.' => ' Job testing assigment ',
    'New password saved.' => 'Новый пароль сохранен',
    'Register' => '@Регистрация@',
    'Sorry, we are unable to resend verification email for the provided email address.' => 'Извените, не можем позволить дать вам сылку на смену пароля по указанной почте',
    'Sorry, we are unable to reset password for the provided email address.' => 'Извените. не можем предоставить ссылку для изменения пароля по указанной почте. ',
    'Sorry, we are unable to verify your account with provided token.' => 'Извените, не можем подтвердить ваш аккаунт по указанному токену',
    'Thank you for contacting us. We will respond to you as soon as possible.' => 'Спасибо за обратную связь. мы ответим вам как только сможем.',
    'There was an error sending your message.' => 'Ошибка в отпраке сообщения.',
    'Your email has been confirmed!' => 'Ваша почта подтверждена!',
    'error' => 'Ошибка',
    'success' => 'Успех',
    'В последнее время' => 'in recent time',
    'Код потверждения' => 'verification code',
    'Конфигурация для выдоваемых данных кусов валют.' => 'configuration for exchange rate output',
    'Курсы криптовалют.' => 'crypto currency value',
    'Напишите нам.' => 'Contact us',
    'ОСНОВНАЯ ЗАДАЧА: задача повторить сервис' => 'Main objective clone service',
    'Общая нагрузка на сервис.' => 'Current server load',
    'Сылка на сервис' => 'link for service',
    'Тестовое задание' => 'Job testing assignment',
    'документация по уии2.' => 'yii2 documentation',
    'отправить' => 'send',
    'пароль' => 'password',
    'почта' => 'email',
    'содержание' => 'content',
    'тема' => 'subject',
    'технические
                        ресурсы Банка России</a> работают ненадежно. Усложнено получение данных
                        о текущих курсах валют: от разработчиков требуют ставить специальные
                        заголовки, данные не загружаются с первого раза. В следствие чего
                        старые скрипты перестали работать. ' => 'it service bank of russia, is experiencing problems reporting currency exchange rates, devloper are tasked with special headers, data is not loaded from the first request, in relation to what scripts stop working.',
    'Signup' => '',
    'registration' => 'регистрация',
    'Грамотная цепочка зеркалирующих источников курсов в порядке планируемой очереди?' => '',
    'Держу обновления курсов, за час, в оперативной памяти, сохраняя данные в базу в течении часа, в случае падения, и не возможности востановления, получения данных из источников, и заполнения ими. ' => '',
    'Добавление дублирующего ресурса источника данных по курсу валют.' => '',
    'Добавление источника курса валют.' => '',
    'Дополнительно. ' => '',
    'Запись на постояную очередь.' => '',
    'Зачем существует подобный сервис и почему его нужно поддержать' => '',
    'Опубликовать результат публичным репозиторием (github, gitlab, bitbucket' => '',
    'Отображать данные из бд без обращения к сервису.' => '',
    'Предоставление графиков для курсов валют.' => '',
    'Связь' => '',
    'Синхронизировать данные, не нарушая условий сервиса.' => '',
    'Создать миграцию на изменение и откат изменений схемы данных.' => '',
    'Создаю, интерфейс для предоставления, к ресурсу очереди, и нагрузок на сервер, с целью,
                не допускать сверхмаксимальной перегрузки, и падения ресурса.' => '',
    'Составить описание (Readme) необходимых действий для запуска.' => '',
    'Список источников курсов валют.' => '',
    'Функциональность взаимодействия с сервисом оформить в виде компонента/библиотеки.' => '',
    'имя' => '',
    'Please fill out the following fields to signup' => '@@Заполните следующие поля для регистрации@@',
    'frontend' => '@@@frontend@@@',
    'signup' => '@@Регистрация@@',
    'test' => '@@@@',
    'Не можем предоставить смену пароля на указанную почту.' => '@@Sorry, cannot provide password change link for provided email@@',
    'новый пароль сохранен' => '@@new password is saved@@',
    'ошибка' => '@@error@@',
    'почта потверждена' => '@@email is confirmed@@',
    'спасибо за регистрацию' => '@@thank you for signing up@@',
    'успех' => '@@success@@',
];

