<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    ' Дополнительно визуализировать значение изменения курса.' => '',
    ' Тестовое задание.' => '',
    'New password saved.' => '',
    'Register' => '',
    'Signup' => '',
    'Sorry, we are unable to resend verification email for the provided email address.' => '',
    'Sorry, we are unable to reset password for the provided email address.' => '',
    'Sorry, we are unable to verify your account with provided token.' => '',
    'Thank you for contacting us. We will respond to you as soon as possible.' => '',
    'There was an error sending your message.' => '',
    'Your email has been confirmed!' => '',
    'error' => '',
    'registration' => '',
    'success' => '',
    'В последнее время' => '',
    'Грамотная цепочка зеркалирующих источников курсов в порядке планируемой очереди?' => '',
    'Держу обновления курсов, за час, в оперативной памяти, сохраняя данные в базу в течении часа, в случае падения, и не возможности востановления, получения данных из источников, и заполнения ими. ' => '',
    'Добавление дублирующего ресурса источника данных по курсу валют.' => '',
    'Добавление источника курса валют.' => '',
    'Дополнительно. ' => '',
    'Запись на постояную очередь.' => '',
    'Зачем существует подобный сервис и почему его нужно поддержать' => '',
    'Код потверждения' => '',
    'Конфигурация для выдоваемых данных кусов валют.' => '',
    'Курсы криптовалют.' => '',
    'Напишите нам.' => '',
    'ОСНОВНАЯ ЗАДАЧА: задача повторить сервис' => '',
    'Общая нагрузка на сервис.' => '',
    'Опубликовать результат публичным репозиторием (github, gitlab, bitbucket' => '',
    'Отображать данные из бд без обращения к сервису.' => '',
    'Предоставление графиков для курсов валют.' => '',
    'Связь' => '',
    'Синхронизировать данные, не нарушая условий сервиса.' => '',
    'Создать миграцию на изменение и откат изменений схемы данных.' => '',
    'Создаю, интерфейс для предоставления, к ресурсу очереди, и нагрузок на сервер, с целью,
                не допускать сверхмаксимальной перегрузки, и падения ресурса.' => '',
    'Составить описание (Readme) необходимых действий для запуска.' => '',
    'Список источников курсов валют.' => '',
    'Сылка на сервис' => '',
    'Тестовое задание' => '',
    'Функциональность взаимодействия с сервисом оформить в виде компонента/библиотеки.' => '',
    'документация по уии2.' => '',
    'имя' => '',
    'отправить' => '',
    'пароль' => '',
    'почта' => '',
    'содержание' => '',
    'тема' => '',
    'технические
                        ресурсы Банка России</a> работают ненадежно. Усложнено получение данных
                        о текущих курсах валют: от разработчиков требуют ставить специальные
                        заголовки, данные не загружаются с первого раза. В следствие чего
                        старые скрипты перестали работать. ' => '',
    'Please fill out the following fields to signup' => '@@@@',
    'frontend' => '@@@@',
    'signup' => '@@@@',
    'test' => '@@что за @@',
    'Не можем предоставить смену пароля на указанную почту.' => '@@@@',
    'новый пароль сохранен' => '@@@@',
    'ошибка' => '@@@@',
    'почта потверждена' => '@@@@',
    'спасибо за регистрацию' => '@@@@',
    'успех' => '@@@@',
];
